name: Build and Deploy Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'fastapi_fortify/**'
      - 'README.md'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[docs]"

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v3

    - name: Create docs site structure
      run: |
        mkdir -p _site
        cp README.md _site/index.md
        cp -r docs/* _site/
        
        # Create a simple index.html
        cat > _site/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>FastAPI Fortify Documentation</title>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.2.0/github-markdown-light.min.css">
            <style>
                body { 
                    box-sizing: border-box;
                    min-width: 200px;
                    max-width: 980px;
                    margin: 0 auto;
                    padding: 45px;
                    font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif;
                }
                .sidebar {
                    position: fixed;
                    top: 0;
                    left: 0;
                    height: 100vh;
                    width: 250px;
                    background: #f6f8fa;
                    padding: 20px;
                    overflow-y: auto;
                }
                .content {
                    margin-left: 290px;
                    padding: 20px;
                }
                .nav-item {
                    display: block;
                    padding: 8px 16px;
                    text-decoration: none;
                    color: #24292f;
                    border-radius: 6px;
                    margin-bottom: 4px;
                }
                .nav-item:hover {
                    background-color: #d0d7de;
                }
            </style>
        </head>
        <body>
            <div class="sidebar">
                <h3>FastAPI Fortify</h3>
                <nav>
                    <a href="#overview" class="nav-item">Overview</a>
                    <a href="installation.html" class="nav-item">Installation</a>
                    <a href="configuration.html" class="nav-item">Configuration</a>
                    <a href="examples.html" class="nav-item">Examples</a>
                    <a href="api-reference.html" class="nav-item">API Reference</a>
                    <a href="security-guide.html" class="nav-item">Security Guide</a>
                    <a href="performance.html" class="nav-item">Performance</a>
                    <a href="load-testing.html" class="nav-item">Load Testing</a>
                    <a href="troubleshooting.html" class="nav-item">Troubleshooting</a>
                </nav>
            </div>
            <div class="content markdown-body" id="content">
                <h1>FastAPI Fortify 🛡️</h1>
                <p><strong>Enterprise-grade security middleware for FastAPI applications with zero configuration required.</strong></p>
                
                <div id="overview">
                    <h2>Overview</h2>
                    <p>FastAPI Fortify provides comprehensive, production-ready security features that protect your FastAPI applications from common web threats including SQL injection, XSS, bot attacks, brute force attempts, and more.</p>
                </div>

                <h2>🚀 Quick Start</h2>
                <h3>Installation</h3>
                <pre><code>pip install fastapi-fortify</code></pre>

                <h3>Basic Usage</h3>
                <pre><code>from fastapi import FastAPI
from fastapi_fortify import SecurityMiddleware

app = FastAPI()
app.add_middleware(SecurityMiddleware)  # That's it! 🎉

@app.get("/")
async def hello():
    return {"message": "Hello, secure world!"}</code></pre>

                <h2>🛡️ Features</h2>
                <ul>
                    <li><strong>🔥 WAF Protection</strong> - Blocks SQL injection, XSS, path traversal, command injection</li>
                    <li><strong>🤖 Bot Detection</strong> - Advanced behavioral analysis and user agent filtering</li>
                    <li><strong>🚫 IP Blocklist</strong> - Static/dynamic blocking with threat intelligence feeds</li>
                    <li><strong>⏱️ Rate Limiting</strong> - Sliding window algorithms with Redis/memory backends</li>
                    <li><strong>👤 Auth Monitoring</strong> - Brute force detection and webhook processing</li>
                    <li><strong>📊 Management API</strong> - RESTful endpoints for monitoring and configuration</li>
                </ul>

                <h2>📚 Documentation</h2>
                <p>Explore the documentation using the navigation menu on the left.</p>
            </div>
        </body>
        </html>
        EOF

    - name: Convert Markdown files to HTML
      run: |
        for file in _site/*.md; do
          if [ "$file" != "_site/index.md" ]; then
            base=$(basename "$file" .md)
            python << EOF
import markdown
import sys

with open('$file', 'r') as f:
    content = f.read()

html = markdown.markdown(content, extensions=['codehilite', 'toc'])

with open('_site/$base.html', 'w') as f:
    f.write(f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{base.title().replace('-', ' ')} - FastAPI Fortify</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.2.0/github-markdown-light.min.css">
    <style>
        body {{ 
            box-sizing: border-box;
            min-width: 200px;
            max-width: 980px;
            margin: 0 auto;
            padding: 45px;
        }}
        .back-link {{
            margin-bottom: 20px;
        }}
        .back-link a {{
            color: #0969da;
            text-decoration: none;
        }}
    </style>
</head>
<body class="markdown-body">
    <div class="back-link">
        <a href="index.html">← Back to Documentation</a>
    </div>
    {html}
</body>
</html>''')
EOF
          fi
        done
        
        # Install markdown for conversion
        pip install markdown

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: '_site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2